AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  IAM Stack to support Partners to integrate ACE Salesfore Connector

Parameters:
  PartnerIdParameter:
    Type: Number
    Description: Your Partner ID (SPMS ID) can be found https://partnercentral.awspartner.com/scorecardredirect
  StageParameter:
    Type: String
    AllowedValues:
      - alpha
      - beta
      - prod
    Default: beta
    Description: Choose Stage of Integration for Testing(beta) or Production(prod)
  ACEKmsEncryptionArn:
    Type: String
    Description: The ACE Team will provide a specific KMS Key Arn per Stage after whitelisting
    Default: arn:aws:kms:us-west-2:*:key/*

Resources:
  AceRequiredIAMRole:
    Type: AWS::IAM::Role # Docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
    Properties:
      RoleName: !Sub "APN-ACE-${PartnerIdParameter}-AccessUser-${StageParameter}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !Ref AWS::AccountId
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: ReadAceBucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListObjects
                  - s3:PutObjectAcl
                  - s3:DeleteObjectTagging
                  - s3:DeleteObject
                  - s3:GetObjectTagging
                  - s3:PutObjectTagging
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::ace-apn-${PartnerIdParameter}-${StageParameter}-us-west-2/*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::ace-apn-${PartnerIdParameter}-${StageParameter}-us-west-2"
        - PolicyName: GrantKMSAccessForAceBucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource: !Ref ACEKmsEncryptionArn
