name: Deploy to AWS Serverless Application Repository

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SAM Publish
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STACK_NAME: ${{ vars.STACK_NAME }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_PREFIX: ${{ vars.S3_PREFIX }}
          PARAMETER_OVERRIDES: ${{ vars.PARAMETER_OVERRIDES }}
      run: |
        CURRENTVERSION = $(<VERSION)
        sam package --template template.yaml --output-template-file packaged.yaml --resolve-s3 
        sam publish --template packaged.yaml --region us-west-2 --semantic-version ${CURRENTVERSION}	
